# Generated by Django 4.1.7 on 2023-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "profile_pic",
                    models.FileField(max_length=250, null=True, upload_to="prof_pic/"),
                ),
            ],
        ),
    ]
