# Generated by Django 4.1.7 on 2023-03-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Demo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="demo",
            new_name="Demo_Models",
        ),
    ]
